# Generated by Django 3.2.3 on 2021-05-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievement_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='content',
        ),
    ]
